create table Person (
    id int generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(200) not null unique,
    login varchar(100) not null unique,
    password varchar(150) not null unique
);

