create table orders (
    id int generated by default as identity primary key,
    cost int check ( cost > 0 ) not null,
    person_id int references person(id) on delete set null,
    date_of_create timestamp not null,
    status varchar(100) check ( status in ('ASSEMBLY','SENT','READY')) default ('ASSEMBLY') not null
);

